### ISSUE TITLE
Data column name issues

### ISSUE THREAD

**Issue by benkeser** [benkeser/slapnap#39] opened 2021-05-21 20:05 UTC
@bdwilliamson could you please try to run the following code and check the output. The goal is to use `slapnap` to retrieve a formatted data set.

Replace `/your/path` below with path to empty folder. 

```bash
docker run \
  -it \
  -e nab="10-1074" \
  -e outcome="sens" \
  -e return="data" \
  -v /your/path:/home/output \
  slapnap/slapnap \
  /bin/bash
```

I get this very bizarre behavior where the column names come out looking all wonky. However, I run the container interactively, if I execute this line from `run_analysis.sh` *twice* things work: 

```bash
Rscript /home/lib/06_return_requested_objects.R >> $log_file 2>&1
```

Feel like this might just be a weird issue with how directories are mounted. It's a very strange error, because I see no reason based on `06_return_requested_objects.R` that anything should change between the two runs.

**Comment by benkeser** [comment] 2021-05-21 20:29
Apparently this happens for other `nab`'s. E.g., have confirmed this for `PGT121` and `PGT145`. 

However, it doesn't happen for all `nab`'s. E.g., `VRC26.08` works.

**Comment by benkeser** [comment] 2021-05-21 20:30
I guess an ad-hoc solution would be to always run this line twice:

```bash
Rscript /home/lib/06_return_requested_objects.R >> $log_file 2>&1
```

But it's such a bizarre error, I kind of want to understand it.

**Comment by bdwilliamson** [comment] 2021-05-21 20:45
Can you be a bit more specific about what "wonky" means in this context? 

I've just run 10-1074, PGT121, PGT145, and VRC26.08 on my Linux machine, and the column names appear to be both consistent across nAbs (e.g., "seq.id.lanl", "seq.id.catnap", followed by "ic50", "ic80", "iip", "sens", geographic region vars, subtype vars, and hxb2 vars [starting at position 1]) and what I would expect to see. 

Currently running on my Windows machine to see if I can find different behavior there.

**Comment by benkeser** [comment] 2021-05-21 20:49
> what "wonky" means in this context?

Ha, good question. In some iterations, it's just `0`'s and `1`'s in the first row. In others it's an incomplete string of actual column names (e.g., the first 1000 columns will have `hxb` in the column name, but then the rest of the columns won't have names.

I'm on a Mac in case that helps. Maybe some weird behavior of `write.csv` induced by having a mounted directory on my system. I don't know. It's honestly baffling.

**Comment by bdwilliamson** [comment] 2021-05-21 21:07
Well that's super strange. I just tested on Windows for the same four nAbs and didn't get any strange results. 

There are four places where I think an error could occur: 
1. When the dataset is created in 02_compile_analysis_dataset.R
2. When the dataset is read back into memory in 06_return_requested_objects.R (using read.csv)
3. When the dataset names are cleaned up using clean_analysis_dataset (from 00_utils.R)
4. When the dataset with new names is saved to the output directory (using write.csv)

If you have time to step through and see where the error is coming in, that would be great, since I can't seem to reproduce the error (not entirely sure why that would be??). And/or we could try to get around this by switching to readr::read_csv and readr::write_csv?

**Comment by benkeser** [comment] 2021-05-21 21:59
It’s write.csv that’s the issue. The data.frame looks fine in R. Let me see if I can reproduce on another Mac.

**Comment by bdwilliamson** [comment] 2021-05-21 22:07
Is it write.csv in 02_compile_analysis_dataset or in 06_return_requested_objects? Or both? 

We could get around the first by saving the dataset internally as a .rds file (which should be totally fine). For the second, can you test write_csv to see if that fixes things?

**Comment by benkeser** [comment] 2021-05-21 22:09
06_ 

Yes will try write_csv on Monday.

**Comment by benkeser** [comment] 2021-05-21 23:40
Actually @caggle360, could you try this on your home machine, if possible?

**Comment by bdwilliamson** [comment] 2021-05-21 23:46
Courtney, if you can check this out, please pull the latest code from here (because I've already implemented saveRDS/readRDS throughout internally for dataset i/o, and I've replaced write.csv with write_csv in 06_return_requested_objects.R)

**Comment by caggle360** [comment] 2021-05-24 13:04
No problem! I pulled the latest code, and I am not seeing any problems with the column names on my computer for those 4 nAbs.

**Comment by bdwilliamson** [comment] 2021-05-24 17:36
Thanks, Courtney! David, can you check on your Mac to see if the updates have solved this issue?

**Comment by bdwilliamson** [comment] 2021-07-22 22:20
Resolving this. @benkeser if you're able to check at some point to see if the issue is resolved that would be great.

**Closed as completed by bdwilliamson** 2021-07-22 22:20 UTC
Labels: bug
